name: 'HELfi Platform config: Base'
type: module
core_version_requirement: '^9 || ^10'
dependencies:
  - drupal:toolbar
  - hdbt_admin_tools:hdbt_admin_tools
  - helfi_base_content:helfi_base_content
  - helfi_ckeditor:helfi_ckeditor
  - helfi_image_styles:helfi_image_styles
  - helfi_media:helfi_media
  - helfi_media_chart:helfi_media_chart
  - helfi_media_map:helfi_media_map
  - helfi_media_remote_video:helfi_media_remote_video
  - helfi_node_announcement:helfi_node_announcement
  - helfi_node_survey:helfi_node_survey
  - helfi_node_landing_page:helfi_node_landing_page
  - helfi_node_page:helfi_node_page
  - helfi_paragraphs_accordion:helfi_paragraphs_accordion
  - helfi_paragraphs_banner:helfi_paragraphs_banner
  - helfi_paragraphs_chart:helfi_paragraphs_chart
  - helfi_paragraphs_columns:helfi_paragraphs_columns
  - helfi_paragraphs_contact_card_listing:helfi_paragraphs_contact_card_listing
  - helfi_paragraphs_content_cards:helfi_paragraphs_content_cards
  - helfi_paragraphs_hearings:helfi_paragraphs_hearings
  - helfi_paragraphs_hero:helfi_paragraphs_hero
  - helfi_paragraphs_image:helfi_paragraphs_image
  - helfi_paragraphs_liftup_with_image:helfi_paragraphs_liftup_with_image
  - helfi_paragraphs_list_of_links:helfi_paragraphs_list_of_links
  - helfi_paragraphs_map:helfi_paragraphs_map
  - helfi_paragraphs_phasing:helfi_paragraphs_phasing
  - helfi_paragraphs_popular_services:helfi_paragraphs_popular_services
  - helfi_paragraphs_remote_video:helfi_paragraphs_remote_video
  - helfi_paragraphs_sidebar_text:helfi_paragraphs_sidebar_text
  - helfi_paragraphs_target_group_links:helfi_paragraphs_target_group_links
  - helfi_paragraphs_text:helfi_paragraphs_text
  - helfi_react_search:helfi_react_search
  - helfi_user_roles:helfi_user_roles
  - publication_date:publication_date
  - stomp:stomp
