
block.settings.telia_ace_widget:
  type: block_settings
  label: 'Block config translation for Telia ACE widget'
  mapping:
    chat_id:
      type: text
      label: 'Chat widget ID'
    chat_title:
      type: text
      label: 'Chat button label'

helfi_platform_config.redirect_cleaner:
  type: config_object
  label: 'Redirect cleaner'
  mapping:
    enable:
      type: boolean
      label: 'Enable redirect cleaner'
    expire_after:
      type: string
      label: 'Expire after'
      description: 'Relative strtotime() string, e.g. "-6 months" or "-1 year"'
    action:
      type: string
      label: 'Action'
      description: 'Cleanup action: "unpublish" or "delete"'


helfi_platform_config.e2e_test_users:
  type: config_object
  mapping:
    users:
      type: sequence
      sequence:
        type: mapping
        mapping:
          username:
            type: string

# Default value.
field.value.location:
  type: mapping
  label: Default value
  mapping:
    latitude:
      type: float
      label: Latitude
    longitude:
      type: float
      label: longitude

# Default value for geo_shape field.
field.value.geo_shape:
  type: mapping
  label: 'Geo Shape'
  mapping:
    value:
      type: string
      label: 'GeoJSON geometry'

# Schema for the Helfi Linkit widget.
field.widget.settings.helfi_linkit:
  type: field.widget.settings.link_default
  label: 'Helfi Linkit widget settings'
  mapping:
    linkit_profile:
      type: string
      label: 'Linkit profile'
    linkit_auto_link_text:
      type: boolean
      label: 'Automatically populate link text from entity label'
