content:
  field_content:
    settings:
      title: Paragraf
  field_hero:
    settings:
      title: Paragraf
  field_lower_content:
    settings:
      title: Paragraf
  field_sidebar_content:
    settings:
      title: Paragraf
