display:
  default:
    display_title: Oletus
    display_options:
      exposed_form:
        options:
          submit_button: Käytä
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      pager:
        options:
          tags:
            next: Seuraava
            previous: Edellinen
            first: Ensimmäinen
            last: Viimeinen
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
      arguments:
        id:
          exception:
            title: Kaikki
  unit_services:
    display_title: Lohko
